extends:
  - "plugin:vue-libs/recommended"
env:
  browser: true
  es6: true
parser: "vue-eslint-parser"
parserOptions:
  parser: "babel-eslint"
  ecmaVersion: 6
  sourceType: "module"
rules:
  semi: ["error", "always"]  # http://eslint.org/docs/rules/semi
